---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-object-mirror
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ns-object-mirror
  template:
    metadata:
      labels:
        app: ns-object-mirror
    spec:
      serviceAccountName: ns-object-mirror
      containers:
        - name: ns-object-mirror
          image: ghcr.io/DragonStuff/ns-object-mirror:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---

