---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ns-object-mirror
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: ns-object-mirror
rules:
    - apiGroups: [""]
      resources: ["configmaps", "secrets", "namespaces"]
      verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: ns-object-mirror
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: ns-object-mirror
subjects:
    - kind: ServiceAccount
      name: ns-object-mirror
      namespace: default
---
